- name: Linpeas
  hosts: localhost

  tasks:
    - name: Download linpeas
      shell: curl -L https://github.com/peass-ng/PEASS-ng/releases/latest/download/linpeas.sh > /tmp/linpeas.sh
    
    - name: Run Linpeas
      shell: sh /tmp/linpeas.sh -a -q
      register: linpeas

    - debug: var=linpeas.stdout
