---
- name: Manage ngrok TCP Tunnel (for AAP)
  hosts: localhost
  connection: local
  gather_facts: yes

  vars:
    # --- Instructions for AAP ---
    # These variables should be configured as "Extra Variables" in your Job Template.
    # The values here are placeholders.
    ngrok_authtoken: "YOUR_NGROK_AUTHTOKEN_HERE"
    port_to_forward: 22
    tunnel_duration_seconds: 3600 # Keep tunnel alive for 1 hour by default

    # --- Playbook Internal Variables ---
    ngrok_install_dir: "{{ ansible_env.HOME }}/.local/bin"

  tasks:
    - name: Main task block with error handling
      block:
        - name: Set ngrok architecture based on system
          ansible.builtin.set_fact:
            ngrok_arch: "{{ 'arm64' if ansible_architecture == 'aarch64' else 'amd64' }}"
          when: ansible_system == 'Linux'

        - name: DEBUG | Show detected architecture
          ansible.builtin.debug:
            var: ngrok_arch

        - name: Ensure local bin directory exists in user's home
          ansible.builtin.file:
            path: "{{ ngrok_install_dir }}"
            state: directory
            mode: '0755'
          register: dir_creation

        - name: DEBUG | Show directory creation result
          ansible.builtin.debug:
            var: dir_creation

        - name: Download and unarchive ngrok
          ansible.builtin.unarchive:
            src: "https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-{{ ngrok_arch }}.tgz"
            dest: "{{ ngrok_install_dir }}"
            remote_src: yes
            mode: '0755'
          when: ansible_system == 'Linux'
          register: unarchive_result

        - name: DEBUG | Show unarchive result
          ansible.builtin.debug:
            var: unarchive_result

        - name: Add ngrok authtoken
          ansible.builtin.command:
            cmd: "{{ ngrok_install_dir }}/ngrok config add-authtoken {{ ngrok_authtoken }}"
          no_log: true
          changed_when: false
          environment:
            HOME: "{{ ansible_env.HOME }}"
          register: authtoken_result

        - name: DEBUG | Show authtoken command result
          ansible.builtin.debug:
            var: authtoken_result

        - name: Start ngrok TCP tunnel in the background
          ansible.builtin.command: "{{ ngrok_install_dir }}/ngrok tcp {{ port_to_forward }} --log=stdout"
          async: "{{ tunnel_duration_seconds + 300 }}" # Give async a buffer
          poll: 0     # Return immediately
          register: ngrok_process

        - name: DEBUG | Show async process start result
          ansible.builtin.debug:
            var: ngrok_process

        - name: Wait for ngrok API to become available
          ansible.builtin.wait_for:
            port: 4040
            host: 127.0.0.1
            delay: 2
            timeout: 10
          register: ngrok_api_check
          until: ngrok_api_check is succeeded
          retries: 5

        - name: DEBUG | Show API availability check result
          ansible.builtin.debug:
            var: ngrok_api_check

        - name: Get tunnel information from ngrok API
          ansible.builtin.uri:
            url: http://127.0.0.1:4040/api/tunnels
            method: GET
            return_content: yes
          register: ngrok_tunnels_raw
          until: ngrok_tunnels_raw.content is defined and ((ngrok_tunnels_raw.content | from_json).tunnels | selectattr('proto', 'equalto', 'tcp') | list | length) > 0
          retries: 5
          delay: 2

        - name: DEBUG | Show raw API response from ngrok
          ansible.builtin.debug:
            var: ngrok_tunnels_raw.content

        - name: Display the public tunnel address
          ansible.builtin.debug:
            msg:
              - "------------------------------------------------------------"
              - "✅ ngrok tunnel is active!"
              - "Forwarding: tcp://127.0.0.1:{{ port_to_forward }}"
              - "Public Address: {{ ((ngrok_tunnels_raw.content | from_json).tunnels | selectattr('proto', 'equalto', 'tcp') | first).public_url }}"
              - "------------------------------------------------------------"
              - " "
              - "Playbook is now paused for {{ tunnel_duration_seconds }} seconds to keep the tunnel alive."

        - name: Pause execution to keep the tunnel alive (AAP compatible)
          ansible.builtin.pause:
            seconds: "{{ tunnel_duration_seconds }}"

      rescue:
        - name: Ensure ngrok process is terminated on failure
          ansible.builtin.command: "pkill ngrok"
          changed_when: false
          failed_when: false

      always:
        - name: Clean up the background ngrok process on exit
          ansible.builtin.async_status:
            jid: "{{ ngrok_process.ansible_job_id }}"
          args:
            mode: cleanup
          when: ngrok_process is defined and ngrok_process.ansible_job_id is defined
          changed_when: false

